name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libcurl4-openssl-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build

      - name: Build project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cd build && ctest --output-on-failure
